// import type { Metadata } from 'next';
// import { Roboto } from 'next/font/google';
// import './globals.css';

// import { NextUIProvider } from '@nextui-org/react';
// import Header from './test/components/Header';

// const roboto = Roboto({ weight: '400', subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={roboto.className}>
//         <NextUIProvider>
//           <Header />
//           {children}
//         </NextUIProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import { NextUIProvider } from '@nextui-org/react';
import Header from './test/components/Header';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={}>
        <NextUIProvider>
          <Header />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
