import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import { NextUIProvider } from '@nextui-org/react';
import Header from './test/components/Header';
// import MegaMenu from './test/components/MegaMenu';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextUIProvider>
          <div className="max-w-7xl w-full mx-auto">
            <Header className="max-w-7xl w-full mx-auto" />
            {/* <MegaMenu /> */}
            {children}
          </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
